runtime: python39  # 使用するPythonのバージョン
entrypoint: gunicorn -b :$PORT app:app  # Gunicornを使用してアプリケーションを実行するコマンド
env: standard  # 環境のタイプ（standardまたはflexible）

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto