runtime: python39  # 使用するPythonのバージョン
entrypoint: gunicorn -b :$PORT app:app  # Gunicornを使用してアプリケーションを実行するコマンド
env: standard  # 環境のタイプ（standardまたはflexible）

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:
  DB_USER: 'testuser-1'
  DB_PASSWORD: 'test0001'
  DB_NAME: 'testDB-20240504'
  DB_CONNECTION_NAME: 'gae-sample-site-422100:asia-northeast1:gae-sample-site-20240504'

